### ISSUE TITLE
English section of v.1.0-600 release notes is in German

### ISSUE THREAD

**Issue by 007revad** [toafez/LogAnalysis#3]
The English section of v.1.0-600 release notes is in German here https://github.com/toafez/LogAnalysis/releases/tag/1.0-600 

Did you copy and paste the notes and forget to translate them?

Haben Sie die Notizen kopiert und eingefügt und vergessen, sie zu übersetzen?

**Comment by toafez** [comment]
Hi!
Thanks for the hint. Since my English is not really good, I have the texts translated by DeepL. Apparently I have copied back the wrong text.

**Comment by toafez** [comment]
Done
