### ISSUE TITLE
Feature Request: Case insensitive search option

### ISSUE THREAD

**Issue by 007revad** [toafez/LogAnalysis#4]
It would be nice if LogAnalysis had a case insensitive option.

I often search for something I know is in the log and LogAnalysis doesn't find it. Then I realise it has a capitol letter in the log and I was searching for all lower case.

**Comment by toafez** [comment]
Hello and thank you for your comment.

I don't have much time right now, but I'll check it out very soon. But it seems to be a solvable problem.

toafez

**Comment by toafez** [comment]
Hi!

I added a checkbox to select whether the search should be case sensitive or not. You can download the new SPK here: https://github.com/toafez/LogAnalysis/releases

Have fun with LogAnalysis

**Comment by 007revad** [comment]
That was fast. Thank you!

I appreciate your work. LogAnalysis deserves a lot more stars.
