### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 007revad** [toafez/LogAnalysis#7]
It would be great if LogAnalysis supported Boolean searches. If that's not possible or too hard, then maybe allow searching in the current search results.

Another suggestion is make the search box have a drop down list of previous search terms that were entered.

**Comment by toafez** [comment]
Hi!

First, about your second suggestion. The HTML form already uses the attribute "autocomplete=on". This means that when autocomplete is enabled, the browser will automatically complete values in a drop-down list based on values the user previously entered. You can find further information here: [https://www.w3schools.com/tags/att_form_autocomplete.asp](https://www.w3schools.com/tags/att_form_autocomplete.asp)

I could certainly also store all entries line by line in a kind of history file and offer them for selection in a drop-down list, but I think this approach is less practical.

And about your suggestion regarding the Boolean search. I would have to look at that first and check whether or how I can implement it. So I can't say much about it at the moment. But I'll look into it

toafez
