### ISSUE TITLE
Search strings containing a " don't work

### ISSUE THREAD

**Issue by 007revad** [toafez/LogAnalysis#8]
I was trying to search for `Invalid json format: {"compatibility_interval` but when I click on "Start search.." the search text box clears and the search finds every line in the log.

If I try escaping the `"` with `\"` when I click "Start search..." the search text box changes from 
`Invalid json format: {\"compatibility_interval` 
to 
`Invalid json format: {`

**Comment by toafez** [comment]
Hi!
I am not very familiar with regular expressions, bracket expressions and grep searches. I had received assistance from someone who is much more familiar with them. I will certainly try to find a solution to the problem you described, but it is a considerable effort for me. So it might take some time. 

toafez

**Comment by 007revad** [comment]
Probably the best option would be giving the user a choice of plain text or regex. Maybe just a simple "Regex" checkbox".

Take you time. Thanks.
